name: Build and deploy docs

on:
  push:
   branches:
    - master

jobs:
 build_docs:
   name: Build docs and deploy to gh-pages
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v6.0.2
     - name: Set up Python 3.14
       uses: actions/setup-python@v6.2.0
       with:
         python-version: "3.14"
     - name: Install uv
       uses: astral-sh/setup-uv@v5
     - name: Install dependencies
       run: uv sync
     - name: Get PR number
       uses: jwalton/gh-find-current-pr@v1
       id: findPr
       with:
         github-token: ${{ secrets.GITHUB_TOKEN }}
     - name: Set commit message
       run: |
         if [ -z "$PR" ]
         then
           echo "COMMIT_MESSAGE=docs: Update docs" >> $GITHUB_ENV
         else
           echo "COMMIT_MESSAGE=docs: Update docs for #$PR" >> $GITHUB_ENV
         fi
       env:
         PR: ${{ steps.findPr.outputs.pr }}
     - name: Build docs
       run: make docs
     - name: Deploy on gh-pages
       uses: JamesIves/github-pages-deploy-action@v4
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
         branch: gh-pages
         folder: docs
         commit-message: ${{ env.COMMIT_MESSAGE }}
         clean: true
